### ISSUE TITLE
Make marketdata client as seperate git repo

### ISSUE THREAD

**Issue by naveenvhegde** [anandkulkarnisg/repogit#1]

**Comment by anandkulkarnisg** [comment]
for me its easy to maintain all my contrib in one repogit folder locally :) , that way makes life. Maintaining multiple repositories locally for me is bit of head ache.

**Comment by naveenvhegde** [comment]
You can still use other repo under 1 repo as git submodule. If someone wants to contribute only to marketdata client, it is not possible with the current setup.

**Comment by anandkulkarnisg** [comment]
agreed will set up one for this.

**Comment by anandkulkarnisg** [comment]
https://github.com/anandkulkarnisg/MarketDataClient , done now. :)
